[package]
name = "parsley-rust"
version = "0.1.0"
authors = ["Prashanth Mundkur <prashanth.mundkur@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
log = "0.4.8"
env_logger = "0.7.0"
log-panics = "2.0.0"
