unstable_features = true
edition = "2018"

hard_tabs = false
newline_style = "Unix"

max_width = 100

wrap_comments = true

spaces_around_ranges = true
space_after_colon = true
space_before_colon = false

fn_args_layout = "Compressed"
fn_single_line = true

struct_field_align_threshold = 20

match_block_trailing_comma = true
trailing_semicolon = false
