// Copyright (c) 2019-2021 SRI International.
// All rights reserved.
//
//    This file is part of the Parsley parser.
//
//    Parsley is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Parsley is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.
use super::pdf_obj::PDFObjT;
use crate::pdf_lib::common_data_structures::{
    mk_array_of_dict_typchk, mk_generic_array_typchk, mk_generic_dict_typchk,
    mk_generic_indirect_array_typchk, mk_generic_indirect_dict_typchk,
    mk_generic_indirect_stream_typchk, mk_name_check, name_dictionary,
};
use crate::pdf_lib::number_tree::number_tree;
use crate::pdf_lib::pdf_prim::NameT;
use crate::pdf_lib::pageobject::pageobject_type;
use crate::pdf_lib::appearance::appearance_type;
use crate::pdf_lib::arrayof_4annotbordercharacteristics::arrayof_4annotbordercharacteristics_type;
use crate::pdf_lib::arrayof_4numberscolorannotation::arrayof_4numberscolorannotation_type;
use crate::pdf_lib::optcontentgroup::optcontentgroup_type;
use crate::pdf_lib::optcontentmembership::optcontentmembership_type;
use crate::pdf_lib::arrayoffilespecifications::arrayoffilespecifications_type;
use crate::pdf_lib::filespecification::filespecification_type;
use crate::pdf_lib::annotpopup::annotpopup_type;
use crate::pdf_lib::stream::stream_type;
use crate::pdf_lib::annottext::annottext_type;
use crate::pdf_lib::annotlink::annotlink_type;
use crate::pdf_lib::annotfreetext::annotfreetext_type;
use crate::pdf_lib::annotline::annotline_type;
use crate::pdf_lib::annotsquare::annotsquare_type;
use crate::pdf_lib::annotcircle::annotcircle_type;
use crate::pdf_lib::annotpolygon::annotpolygon_type;
use crate::pdf_lib::annothighlight::annothighlight_type;
use crate::pdf_lib::annotunderline::annotunderline_type;
use crate::pdf_lib::annotsquiggly::annotsquiggly_type;
use crate::pdf_lib::annotstrikeout::annotstrikeout_type;
use crate::pdf_lib::annotcaret::annotcaret_type;
use crate::pdf_lib::annotstamp::annotstamp_type;
use crate::pdf_lib::annotink::annotink_type;
use crate::pdf_lib::annotpopup::annotpopup_type;
use crate::pdf_lib::annotfileattachment::annotfileattachment_type;
use crate::pdf_lib::annotsound::annotsound_type;
use crate::pdf_lib::annotmovie::annotmovie_type;
use crate::pdf_lib::annotscreen::annotscreen_type;
use crate::pdf_lib::annotwidget::annotwidget_type;
use crate::pdf_lib::annotprintermark::annotprintermark_type;
use crate::pdf_lib::annotwatermark::annotwatermark_type;
use crate::pdf_lib::annot3d::annot3d_type;
use crate::pdf_lib::annotredact::annotredact_type;
use crate::pdf_lib::annotprojection::annotprojection_type;
use crate::pdf_lib::annotrichmedia::annotrichmedia_type;
use crate::pdf_lib::arrayofnumbersgeneral::arrayofnumbersgeneral_type;
use crate::pdf_lib::arrayof_2lineendingsnames::arrayof_2lineendingsnames_type;
use crate::pdf_lib::borderstyle::borderstyle_type;
use crate::pdf_lib::arrayof_4numberscolorannotation::arrayof_4numberscolorannotation_type;
use crate::pdf_lib::bordereffect::bordereffect_type;
use crate::pdf_lib::measurerl::measurerl_type;
use crate::pdf_lib::measuregeo::measuregeo_type;
use crate::pdf_lib::arrayofarrayspaths::arrayofarrayspaths_type;
use crate::pdf_lib::exdata3dmarkup::exdata3dmarkup_type;
use crate::pdf_lib::exdatamarkupgeo::exdatamarkupgeo_type;
use crate::pdf_lib::exdataprojection::exdataprojection_type;
    let choices_type = ChoicesPred(
        String::From("Invalid Type"), 
        vec![ 
         PDFObjT::Name(NameT::new(Vec::from("Annot"))),
           ],
     );
    let choices_subtype = ChoicesPred(
        String::From("Invalid Subtype"), 
        vec![ 
         PDFObjT::Name(NameT::new(Vec::from("PolyLine"))),
           ],
     );
    let choices_rt = ChoicesPred(
        String::From("Invalid RT"), 
        vec![ 
         PDFObjT::Name(NameT::new(Vec::from("R"))),
         PDFObjT::Name(NameT::new(Vec::from("Group"))),
           ],
     );
    let choices_it = ChoicesPred(
        String::From("Invalid IT"), 
        vec![ 
         PDFObjT::Name(NameT::new(Vec::from("PolygonCloud"))),
         PDFObjT::Name(NameT::new(Vec::from("PolyLineDimension)"))),
         PDFObjT::Name(NameT::new(Vec::from("PolygonDimension)"))),
           ],
     );
pub fn annotpolyline_type(tctx: &mut TypeCheckContext) -> Rc<TypeCheck> {
    let type_field = DictEntry { 
       key: Vec::from("Type"), 
       chk: choices_type(tctx),
       opt: DictKeySpec::Optional,
    }; 
    let subtype_field = DictEntry { 
       key: Vec::from("Subtype"), 
       chk: choices_subtype(tctx),
       opt: DictKeySpec::Required,
    }; 
    let rect_field = DictEntry { 
       key: Vec::from("Rect"), 
       opt: DictKeySpec::Required,
    }; 
    let contents_field = DictEntry { 
       key: Vec::from("Contents"), 
       opt: DictKeySpec::Optional,
    }; 
    let p_field = DictEntry { 
       key: Vec::from("P"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         p_type,
         a_type,
         g_type,
         e_type,
         o_type,
         b_type,
         j_type,
         e_type,
         c_type,
         t_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let nm_field = DictEntry { 
       key: Vec::from("NM"), 
       opt: DictKeySpec::Optional,
    }; 
    let m_field = DictEntry { 
       key: Vec::from("M"), 
       opt: DictKeySpec::Optional,
    }; 
    let f_field = DictEntry { 
       key: Vec::from("F"), 
       opt: DictKeySpec::Optional,
    }; 
    let ap_field = DictEntry { 
       key: Vec::from("AP"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         p_type,
         p_type,
         e_type,
         a_type,
         r_type,
         a_type,
         n_type,
         c_type,
         e_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let as_field = DictEntry { 
       key: Vec::from("AS"), 
       opt: DictKeySpec::Optional,
    }; 
    let border_field = DictEntry { 
       key: Vec::from("Border"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         __type,
         4_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         b_type,
         o_type,
         r_type,
         d_type,
         e_type,
         r_type,
         c_type,
         h_type,
         a_type,
         r_type,
         a_type,
         c_type,
         t_type,
         e_type,
         r_type,
         i_type,
         s_type,
         t_type,
         i_type,
         c_type,
         s_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let c_field = DictEntry { 
       key: Vec::from("C"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         __type,
         4_type,
         n_type,
         u_type,
         m_type,
         b_type,
         e_type,
         r_type,
         s_type,
         c_type,
         o_type,
         l_type,
         o_type,
         r_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         a_type,
         t_type,
         i_type,
         o_type,
         n_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let structparent_field = DictEntry { 
       key: Vec::from("StructParent"), 
       opt: DictKeySpec::Optional,
    }; 
    let oc_field = DictEntry { 
       key: Vec::from("OC"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         o_type,
         p_type,
         t_type,
         c_type,
         o_type,
         n_type,
         t_type,
         e_type,
         n_type,
         t_type,
         g_type,
         r_type,
         o_type,
         u_type,
         p_type,
         ,_type,
         o_type,
         p_type,
         t_type,
         c_type,
         o_type,
         n_type,
         t_type,
         e_type,
         n_type,
         t_type,
         m_type,
         e_type,
         m_type,
         b_type,
         e_type,
         r_type,
         s_type,
         h_type,
         i_type,
         p_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let af_field = DictEntry { 
       key: Vec::from("AF"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         f_type,
         i_type,
         l_type,
         e_type,
         s_type,
         p_type,
         e_type,
         c_type,
         i_type,
         f_type,
         i_type,
         c_type,
         a_type,
         t_type,
         i_type,
         o_type,
         n_type,
         s_type,
         ]_type,
         ;_type,
         [_type,
         f_type,
         i_type,
         l_type,
         e_type,
         s_type,
         p_type,
         e_type,
         c_type,
         i_type,
         f_type,
         i_type,
         c_type,
         a_type,
         t_type,
         i_type,
         o_type,
         n_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let ca_field = DictEntry { 
       key: Vec::from("ca"), 
       opt: DictKeySpec::Optional,
    }; 
    let ca_field = DictEntry { 
       key: Vec::from("CA"), 
       opt: DictKeySpec::Optional,
    }; 
    let bm_field = DictEntry { 
       key: Vec::from("BM"), 
       opt: DictKeySpec::Optional,
    }; 
    let lang_field = DictEntry { 
       key: Vec::from("Lang"), 
       opt: DictKeySpec::Optional,
    }; 
    let t_field = DictEntry { 
       key: Vec::from("T"), 
       opt: DictKeySpec::Optional,
    }; 
    let popup_field = DictEntry { 
       key: Vec::from("Popup"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         p_type,
         o_type,
         p_type,
         u_type,
         p_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let rc_field = DictEntry { 
       key: Vec::from("RC"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         s_type,
         t_type,
         r_type,
         e_type,
         a_type,
         m_type,
         ]_type,
         ;_type,
         [_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let creationdate_field = DictEntry { 
       key: Vec::from("CreationDate"), 
       opt: DictKeySpec::Optional,
    }; 
    let irt_field = DictEntry { 
       key: Vec::from("IRT"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         t_type,
         e_type,
         x_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         l_type,
         i_type,
         n_type,
         k_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         f_type,
         r_type,
         e_type,
         e_type,
         t_type,
         e_type,
         x_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         l_type,
         i_type,
         n_type,
         e_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         s_type,
         q_type,
         u_type,
         a_type,
         r_type,
         e_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         c_type,
         i_type,
         r_type,
         c_type,
         l_type,
         e_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         p_type,
         o_type,
         l_type,
         y_type,
         g_type,
         o_type,
         n_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         h_type,
         i_type,
         g_type,
         h_type,
         l_type,
         i_type,
         g_type,
         h_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         u_type,
         n_type,
         d_type,
         e_type,
         r_type,
         l_type,
         i_type,
         n_type,
         e_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         s_type,
         q_type,
         u_type,
         i_type,
         g_type,
         g_type,
         l_type,
         y_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         s_type,
         t_type,
         r_type,
         i_type,
         k_type,
         e_type,
         o_type,
         u_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         c_type,
         a_type,
         r_type,
         e_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         s_type,
         t_type,
         a_type,
         m_type,
         p_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         i_type,
         n_type,
         k_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         p_type,
         o_type,
         p_type,
         u_type,
         p_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         f_type,
         i_type,
         l_type,
         e_type,
         a_type,
         t_type,
         t_type,
         a_type,
         c_type,
         h_type,
         m_type,
         e_type,
         n_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         s_type,
         o_type,
         u_type,
         n_type,
         d_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         m_type,
         o_type,
         v_type,
         i_type,
         e_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         s_type,
         c_type,
         r_type,
         e_type,
         e_type,
         n_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         w_type,
         i_type,
         d_type,
         g_type,
         e_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         p_type,
         r_type,
         i_type,
         n_type,
         t_type,
         e_type,
         r_type,
         m_type,
         a_type,
         r_type,
         k_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         w_type,
         a_type,
         t_type,
         e_type,
         r_type,
         m_type,
         a_type,
         r_type,
         k_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         3_type,
         d_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         r_type,
         e_type,
         d_type,
         a_type,
         c_type,
         t_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         p_type,
         r_type,
         o_type,
         j_type,
         e_type,
         c_type,
         t_type,
         i_type,
         o_type,
         n_type,
         ,_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         r_type,
         i_type,
         c_type,
         h_type,
         m_type,
         e_type,
         d_type,
         i_type,
         a_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let subj_field = DictEntry { 
       key: Vec::from("Subj"), 
       opt: DictKeySpec::Optional,
    }; 
    let rt_field = DictEntry { 
       key: Vec::from("RT"), 
       chk: choices_rt(tctx),
       opt: DictKeySpec::Optional,
    }; 
    let vertices_field = DictEntry { 
       key: Vec::from("Vertices"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         n_type,
         u_type,
         m_type,
         b_type,
         e_type,
         r_type,
         s_type,
         g_type,
         e_type,
         n_type,
         e_type,
         r_type,
         a_type,
         l_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let le_field = DictEntry { 
       key: Vec::from("LE"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         __type,
         2_type,
         l_type,
         i_type,
         n_type,
         e_type,
         e_type,
         n_type,
         d_type,
         i_type,
         n_type,
         g_type,
         s_type,
         n_type,
         a_type,
         m_type,
         e_type,
         s_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let bs_field = DictEntry { 
       key: Vec::from("BS"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         b_type,
         o_type,
         r_type,
         d_type,
         e_type,
         r_type,
         s_type,
         t_type,
         y_type,
         l_type,
         e_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let ic_field = DictEntry { 
       key: Vec::from("IC"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         __type,
         4_type,
         n_type,
         u_type,
         m_type,
         b_type,
         e_type,
         r_type,
         s_type,
         c_type,
         o_type,
         l_type,
         o_type,
         r_type,
         a_type,
         n_type,
         n_type,
         o_type,
         t_type,
         a_type,
         t_type,
         i_type,
         o_type,
         n_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let be_field = DictEntry { 
       key: Vec::from("BE"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         b_type,
         o_type,
         r_type,
         d_type,
         e_type,
         r_type,
         e_type,
         f_type,
         f_type,
         e_type,
         c_type,
         t_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let it_field = DictEntry { 
       key: Vec::from("IT"), 
       chk: choices_it(tctx),
       opt: DictKeySpec::Optional,
    }; 
    let measure_field = DictEntry { 
       key: Vec::from("Measure"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         m_type,
         e_type,
         a_type,
         s_type,
         u_type,
         r_type,
         e_type,
         r_type,
         l_type,
         ,_type,
         m_type,
         e_type,
         a_type,
         s_type,
         u_type,
         r_type,
         e_type,
         g_type,
         e_type,
         o_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let path_field = DictEntry { 
       key: Vec::from("Path"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         s_type,
         p_type,
         a_type,
         t_type,
         h_type,
         s_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let exdata_field = DictEntry { 
       key: Vec::from("ExData"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         e_type,
         x_type,
         d_type,
         a_type,
         t_type,
         a_type,
         3_type,
         d_type,
         m_type,
         a_type,
         r_type,
         k_type,
         u_type,
         p_type,
         ,_type,
         e_type,
         x_type,
         d_type,
         a_type,
         t_type,
         a_type,
         m_type,
         a_type,
         r_type,
         k_type,
         u_type,
         p_type,
         g_type,
         e_type,
         o_type,
         ,_type,
         e_type,
         x_type,
         d_type,
         a_type,
         t_type,
         a_type,
         p_type,
         r_type,
         o_type,
         j_type,
         e_type,
         c_type,
         t_type,
         i_type,
         o_type,
         n_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    TypeCheck::new(
    tctx,
    "annotpolyline",
    Rc::new(PDFType::Dict(vec![
      type_field,
      subtype_field,
      rect_field,
      contents_field,
      p_field,
      nm_field,
      m_field,
      f_field,
      ap_field,
      as_field,
      border_field,
      c_field,
      structparent_field,
      oc_field,
      af_field,
      ca_field,
      ca_field,
      bm_field,
      lang_field,
      t_field,
      popup_field,
      rc_field,
      creationdate_field,
      irt_field,
      subj_field,
      rt_field,
      vertices_field,
      le_field,
      bs_field,
      ic_field,
      be_field,
      it_field,
      measure_field,
      path_field,
      exdata_field,
   ]))
}