// Copyright (c) 2019-2021 SRI International.
// All rights reserved.
//
//    This file is part of the Parsley parser.
//
//    Parsley is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Parsley is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.
use super::pdf_obj::PDFObjT;
use crate::pdf_lib::common_data_structures::{
    mk_array_of_dict_typchk, mk_generic_array_typchk, mk_generic_dict_typchk,
    mk_generic_indirect_array_typchk, mk_generic_indirect_dict_typchk,
    mk_generic_indirect_stream_typchk, mk_name_check, name_dictionary,
};
use crate::pdf_lib::number_tree::number_tree;
use crate::pdf_lib::pdf_prim::NameT;
use crate::pdf_lib::matrix::matrix_type;
use crate::pdf_lib::resource::resource_type;
use crate::pdf_lib::group::group_type;
use crate::pdf_lib::reference::reference_type;
use crate::pdf_lib::metadata::metadata_type;
use crate::pdf_lib::pagepiece::pagepiece_type;
use crate::pdf_lib::opiversion13::opiversion13_type;
use crate::pdf_lib::opiversion20::opiversion20_type;
use crate::pdf_lib::optcontentgroup::optcontentgroup_type;
use crate::pdf_lib::optcontentmembership::optcontentmembership_type;
use crate::pdf_lib::arrayoffilespecifications::arrayoffilespecifications_type;
use crate::pdf_lib::filespecification::filespecification_type;
use crate::pdf_lib::measurerl::measurerl_type;
use crate::pdf_lib::pointdata::pointdata_type;
use crate::pdf_lib::arrayofcompressionfilternames::arrayofcompressionfilternames_type;
use crate::pdf_lib::arrayofdecodeparams::arrayofdecodeparams_type;
use crate::pdf_lib::filterlzwdecode::filterlzwdecode_type;
use crate::pdf_lib::filterflatedecode::filterflatedecode_type;
use crate::pdf_lib::filtercrypt::filtercrypt_type;
use crate::pdf_lib::filespecification::filespecification_type;
use crate::pdf_lib::arrayofcompressionfilternames::arrayofcompressionfilternames_type;
use crate::pdf_lib::arrayofdecodeparams::arrayofdecodeparams_type;
use crate::pdf_lib::filterlzwdecode::filterlzwdecode_type;
use crate::pdf_lib::filterflatedecode::filterflatedecode_type;
use crate::pdf_lib::filtercrypt::filtercrypt_type;
use crate::pdf_lib::arrayofnamesgeneral::arrayofnamesgeneral_type;
use crate::pdf_lib::_universaldictionary::_universaldictionary_type;
    let choices_type = ChoicesPred(
        String::From("Invalid Type"), 
        vec![ 
         PDFObjT::Name(NameT::new(Vec::from("XObject"))),
           ],
     );
    let choices_subtype = ChoicesPred(
        String::From("Invalid Subtype"), 
        vec![ 
         PDFObjT::Name(NameT::new(Vec::from("Form"))),
           ],
     );
    let choices_formtype = ChoicesPred(
        String::From("Invalid FormType"), 
        vec![ 
         PDFObjT::Name(NameT::new(Vec::from("1"))),
           ],
     );
pub fn xobjectformtrapnet_type(tctx: &mut TypeCheckContext) -> Rc<TypeCheck> {
    let type_field = DictEntry { 
       key: Vec::from("Type"), 
       chk: choices_type(tctx),
       opt: DictKeySpec::Optional,
    }; 
    let subtype_field = DictEntry { 
       key: Vec::from("Subtype"), 
       chk: choices_subtype(tctx),
       opt: DictKeySpec::Required,
    }; 
    let formtype_field = DictEntry { 
       key: Vec::from("FormType"), 
       chk: choices_formtype(tctx),
       opt: DictKeySpec::Optional,
    }; 
    let bbox_field = DictEntry { 
       key: Vec::from("BBox"), 
       opt: DictKeySpec::Required,
    }; 
    let matrix_field = DictEntry { 
       key: Vec::from("Matrix"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         m_type,
         a_type,
         t_type,
         r_type,
         i_type,
         x_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let resources_field = DictEntry { 
       key: Vec::from("Resources"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         r_type,
         e_type,
         s_type,
         o_type,
         u_type,
         r_type,
         c_type,
         e_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let group_field = DictEntry { 
       key: Vec::from("Group"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         g_type,
         r_type,
         o_type,
         u_type,
         p_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let ref_field = DictEntry { 
       key: Vec::from("Ref"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         r_type,
         e_type,
         f_type,
         e_type,
         r_type,
         e_type,
         n_type,
         c_type,
         e_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let metadata_field = DictEntry { 
       key: Vec::from("Metadata"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         m_type,
         e_type,
         t_type,
         a_type,
         d_type,
         a_type,
         t_type,
         a_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let pieceinfo_field = DictEntry { 
       key: Vec::from("PieceInfo"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         p_type,
         a_type,
         g_type,
         e_type,
         p_type,
         i_type,
         e_type,
         c_type,
         e_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let lastmodified_field = DictEntry { 
       key: Vec::from("LastModified"), 
       opt: DictKeySpec::Optional,
    }; 
    let structparent_field = DictEntry { 
       key: Vec::from("StructParent"), 
       opt: DictKeySpec::Optional,
    }; 
    let structparents_field = DictEntry { 
       key: Vec::from("StructParents"), 
       opt: DictKeySpec::Optional,
    }; 
    let opi_field = DictEntry { 
       key: Vec::from("OPI"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         o_type,
         p_type,
         i_type,
         v_type,
         e_type,
         r_type,
         s_type,
         i_type,
         o_type,
         n_type,
         1_type,
         3_type,
         ,_type,
         o_type,
         p_type,
         i_type,
         v_type,
         e_type,
         r_type,
         s_type,
         i_type,
         o_type,
         n_type,
         2_type,
         0_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let oc_field = DictEntry { 
       key: Vec::from("OC"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         o_type,
         p_type,
         t_type,
         c_type,
         o_type,
         n_type,
         t_type,
         e_type,
         n_type,
         t_type,
         g_type,
         r_type,
         o_type,
         u_type,
         p_type,
         ,_type,
         o_type,
         p_type,
         t_type,
         c_type,
         o_type,
         n_type,
         t_type,
         e_type,
         n_type,
         t_type,
         m_type,
         e_type,
         m_type,
         b_type,
         e_type,
         r_type,
         s_type,
         h_type,
         i_type,
         p_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let name_field = DictEntry { 
       key: Vec::from("Name"), 
       opt: DictKeySpec::Optional,
    }; 
    let af_field = DictEntry { 
       key: Vec::from("AF"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         f_type,
         i_type,
         l_type,
         e_type,
         s_type,
         p_type,
         e_type,
         c_type,
         i_type,
         f_type,
         i_type,
         c_type,
         a_type,
         t_type,
         i_type,
         o_type,
         n_type,
         s_type,
         ]_type,
         ;_type,
         [_type,
         f_type,
         i_type,
         l_type,
         e_type,
         s_type,
         p_type,
         e_type,
         c_type,
         i_type,
         f_type,
         i_type,
         c_type,
         a_type,
         t_type,
         i_type,
         o_type,
         n_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let measure_field = DictEntry { 
       key: Vec::from("Measure"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         m_type,
         e_type,
         a_type,
         s_type,
         u_type,
         r_type,
         e_type,
         r_type,
         l_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let ptdata_field = DictEntry { 
       key: Vec::from("PtData"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         p_type,
         o_type,
         i_type,
         n_type,
         t_type,
         d_type,
         a_type,
         t_type,
         a_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let length_field = DictEntry { 
       key: Vec::from("Length"), 
       opt: DictKeySpec::Required,
    }; 
    let filter_field = DictEntry { 
       key: Vec::from("Filter"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         c_type,
         o_type,
         m_type,
         p_type,
         r_type,
         e_type,
         s_type,
         s_type,
         i_type,
         o_type,
         n_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         n_type,
         a_type,
         m_type,
         e_type,
         s_type,
         ]_type,
         ;_type,
         [_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let decodeparms_field = DictEntry { 
       key: Vec::from("DecodeParms"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         d_type,
         e_type,
         c_type,
         o_type,
         d_type,
         e_type,
         p_type,
         a_type,
         r_type,
         a_type,
         m_type,
         s_type,
         ]_type,
         ;_type,
         [_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         l_type,
         z_type,
         w_type,
         d_type,
         e_type,
         c_type,
         o_type,
         d_type,
         e_type,
         ,_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         f_type,
         l_type,
         a_type,
         t_type,
         e_type,
         d_type,
         e_type,
         c_type,
         o_type,
         d_type,
         e_type,
         ,_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         c_type,
         r_type,
         y_type,
         p_type,
         t_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let f_field = DictEntry { 
       key: Vec::from("F"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         f_type,
         i_type,
         l_type,
         e_type,
         s_type,
         p_type,
         e_type,
         c_type,
         i_type,
         f_type,
         i_type,
         c_type,
         a_type,
         t_type,
         i_type,
         o_type,
         n_type,
         ]_type,
         ;_type,
         [_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let ffilter_field = DictEntry { 
       key: Vec::from("FFilter"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         c_type,
         o_type,
         m_type,
         p_type,
         r_type,
         e_type,
         s_type,
         s_type,
         i_type,
         o_type,
         n_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         n_type,
         a_type,
         m_type,
         e_type,
         s_type,
         ]_type,
         ;_type,
         [_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let fdecodeparms_field = DictEntry { 
       key: Vec::from("FDecodeParms"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         d_type,
         e_type,
         c_type,
         o_type,
         d_type,
         e_type,
         p_type,
         a_type,
         r_type,
         a_type,
         m_type,
         s_type,
         ]_type,
         ;_type,
         [_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         l_type,
         z_type,
         w_type,
         d_type,
         e_type,
         c_type,
         o_type,
         d_type,
         e_type,
         ,_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         f_type,
         l_type,
         a_type,
         t_type,
         e_type,
         d_type,
         e_type,
         c_type,
         o_type,
         d_type,
         e_type,
         ,_type,
         f_type,
         i_type,
         l_type,
         t_type,
         e_type,
         r_type,
         c_type,
         r_type,
         y_type,
         p_type,
         t_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let dl_field = DictEntry { 
       key: Vec::from("DL"), 
       opt: DictKeySpec::Optional,
    }; 
    let pcm_field = DictEntry { 
       key: Vec::from("PCM"), 
       opt: DictKeySpec::Optional,
    }; 
    let separationcolornames_field = DictEntry { 
       key: Vec::from("SeparationColorNames"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         a_type,
         r_type,
         r_type,
         a_type,
         y_type,
         o_type,
         f_type,
         n_type,
         a_type,
         m_type,
         e_type,
         s_type,
         g_type,
         e_type,
         n_type,
         e_type,
         r_type,
         a_type,
         l_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let trapregions_field = DictEntry { 
       key: Vec::from("TrapRegions"), 
       chk: Rc::new(PDFType::Disjunct(vec![
         [_type,
         __type,
         u_type,
         n_type,
         i_type,
         v_type,
         e_type,
         r_type,
         s_type,
         a_type,
         l_type,
         d_type,
         i_type,
         c_type,
         t_type,
         i_type,
         o_type,
         n_type,
         a_type,
         r_type,
         y_type,
         ]_type,
]),
       opt: DictKeySpec::Optional,
    }; 
    let trapstyles_field = DictEntry { 
       key: Vec::from("TrapStyles"), 
       opt: DictKeySpec::Optional,
    }; 
    TypeCheck::new(
    tctx,
    "xobjectformtrapnet",
    Rc::new(PDFType::Dict(vec![
      type_field,
      subtype_field,
      formtype_field,
      bbox_field,
      matrix_field,
      resources_field,
      group_field,
      ref_field,
      metadata_field,
      pieceinfo_field,
      lastmodified_field,
      structparent_field,
      structparents_field,
      opi_field,
      oc_field,
      name_field,
      af_field,
      measure_field,
      ptdata_field,
      length_field,
      filter_field,
      decodeparms_field,
      f_field,
      ffilter_field,
      fdecodeparms_field,
      dl_field,
      pcm_field,
      separationcolornames_field,
      trapregions_field,
      trapstyles_field,
   ]))
}